"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tom Bell"
email = "tomb@tombell.dev"

[ui]
default-command = "log"

[aliases]
l = ["log", "-r", "(main..@):: | (main..@)-"]
log-all = ["log", "-r", "all()"]
