"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tom Bell"
email = "tomb@tombell.dev"

[ui]
default-command = "log"
diff-formatter = "delta"

[merge-tools.delta]
diff-args=["--side-by-side", "$left", "$right", "--width=$width"]
diff-expected-exit-codes = [0, 1]

[aliases]
l = ["log", "-r", "(main..@):: | (main..@)-"]
ll = ["log", "-r", "all()"]
